//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloDatemaClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHelloDatemaService")]
    public interface IHelloDatemaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetData", ReplyAction="http://tempuri.org/IHelloDatemaService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetData", ReplyAction="http://tempuri.org/IHelloDatemaService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSTableRowsCount", ReplyAction="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSTableRowsCountResponse")]
        string GetMOLOKO_VSTableRowsCount(string sTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSTableRowsCount", ReplyAction="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSTableRowsCountResponse")]
        System.Threading.Tasks.Task<string> GetMOLOKO_VSTableRowsCountAsync(string sTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSAppointments", ReplyAction="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSAppointmentsResponse")]
        System.Data.DataSet GetMOLOKO_VSAppointments(int iMitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSAppointments", ReplyAction="http://tempuri.org/IHelloDatemaService/GetMOLOKO_VSAppointmentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMOLOKO_VSAppointmentsAsync(int iMitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetDSStreckenplan", ReplyAction="http://tempuri.org/IHelloDatemaService/GetDSStreckenplanResponse")]
        HelloDatemaService.DSStreckenplan GetDSStreckenplan(int iMitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/GetDSStreckenplan", ReplyAction="http://tempuri.org/IHelloDatemaService/GetDSStreckenplanResponse")]
        System.Threading.Tasks.Task<HelloDatemaService.DSStreckenplan> GetDSStreckenplanAsync(int iMitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/PutDSStreckenplan", ReplyAction="http://tempuri.org/IHelloDatemaService/PutDSStreckenplanResponse")]
        HelloDatemaService.HelloDatemaService.PutDSStreckenplanResult PutDSStreckenplan(HelloDatemaService.DSStreckenplan aDSStreckenplan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloDatemaService/PutDSStreckenplan", ReplyAction="http://tempuri.org/IHelloDatemaService/PutDSStreckenplanResponse")]
        System.Threading.Tasks.Task<HelloDatemaService.HelloDatemaService.PutDSStreckenplanResult> PutDSStreckenplanAsync(HelloDatemaService.DSStreckenplan aDSStreckenplan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloDatemaServiceChannel : HelloDatemaClient.ServiceReference1.IHelloDatemaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloDatemaServiceClient : System.ServiceModel.ClientBase<HelloDatemaClient.ServiceReference1.IHelloDatemaService>, HelloDatemaClient.ServiceReference1.IHelloDatemaService {
        
        public HelloDatemaServiceClient() {
        }
        
        public HelloDatemaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloDatemaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloDatemaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloDatemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetMOLOKO_VSTableRowsCount(string sTableName) {
            return base.Channel.GetMOLOKO_VSTableRowsCount(sTableName);
        }
        
        public System.Threading.Tasks.Task<string> GetMOLOKO_VSTableRowsCountAsync(string sTableName) {
            return base.Channel.GetMOLOKO_VSTableRowsCountAsync(sTableName);
        }
        
        public System.Data.DataSet GetMOLOKO_VSAppointments(int iMitarbeiter_id) {
            return base.Channel.GetMOLOKO_VSAppointments(iMitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMOLOKO_VSAppointmentsAsync(int iMitarbeiter_id) {
            return base.Channel.GetMOLOKO_VSAppointmentsAsync(iMitarbeiter_id);
        }
        
        public HelloDatemaService.DSStreckenplan GetDSStreckenplan(int iMitarbeiter_id) {
            return base.Channel.GetDSStreckenplan(iMitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<HelloDatemaService.DSStreckenplan> GetDSStreckenplanAsync(int iMitarbeiter_id) {
            return base.Channel.GetDSStreckenplanAsync(iMitarbeiter_id);
        }
        
        public HelloDatemaService.HelloDatemaService.PutDSStreckenplanResult PutDSStreckenplan(HelloDatemaService.DSStreckenplan aDSStreckenplan) {
            return base.Channel.PutDSStreckenplan(aDSStreckenplan);
        }
        
        public System.Threading.Tasks.Task<HelloDatemaService.HelloDatemaService.PutDSStreckenplanResult> PutDSStreckenplanAsync(HelloDatemaService.DSStreckenplan aDSStreckenplan) {
            return base.Channel.PutDSStreckenplanAsync(aDSStreckenplan);
        }
    }
}
